expensetracker/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from expenses import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    url(r'^calendar/$', views.calendar),
    url(r'^search/$', views.search),
    url(r'^day/(?P<slug>[-\w\d\_]+)/$', views.day_detail, name='day_detail'),
    url(r'^work_day/(?P<slug>[-\w\d\_]+)/$', views.workday_detail, name='workday_detail'),
    url(r'^project/(?P<slug>[-\w\d\_]+)/$', views.project_detail, name='project_detail'),
    url(r'^employee/(?P<slug>[-\w\d\_]+)/$', views.employee_detail, name='employee_detail'),
    url(r'^expense_search/$', views.expense_search),
]

expenses/models.py
import random

import googlemaps
from django.db import models
from django.template.defaultfilters import slugify

PLANSPERMITS = '01'
DEMOLITION = '02'
FOUNDATION = '03'
ROOFGUTTERS = '04'
EXTERIORSIDING = '05'
WINDOWS = '06'
GARAGEDRIVEWAY = '07'
FRAMING = '08'
FINISHCARPENTRY = '09'
SHEETROCKINSULATION = '10'
INTERIORPAINT = '11'
FLOORING = '12'
KITCHEN = '13'
BATHROOMS = '14'
PLUMBINGWORK = '15'
ELECTRICALWORK = '16'
HVACWORK = '17'
APPLIANCES = '18'
YARDLANDSCAPING = '19'
BASEMENTFINISHES = '20'

DIVISION_CHOICES = (
    (PLANSPERMITS, 'Plans/Permits'),
    (DEMOLITION, 'Demolition'),
    (FOUNDATION, 'Foundation'),
    (ROOFGUTTERS, 'Roof/Gutters'),
    (EXTERIORSIDING, 'Exterior/Siding'),
    (WINDOWS, 'Windows'),
    (GARAGEDRIVEWAY, 'Garage/Driveway'),
    (FRAMING, 'Framing'),
    (FINISHCARPENTRY, 'Finish Carpentry'),
    (SHEETROCKINSULATION, 'Sheetrock/Insulation'),
    (INTERIORPAINT, 'Interior Paint'),
    (FLOORING, 'Flooring'),
    (KITCHEN, 'Kitchen'),
    (BATHROOMS, 'Bathrooms'),
    (PLUMBINGWORK, 'Plumbing Work'),
    (ELECTRICALWORK, 'Electrical Work'),
    (HVACWORK, 'HVAC Work'),
    (APPLIANCES, 'Appliances'),
    (YARDLANDSCAPING, 'Yard/Landscaping'),
    (BASEMENTFINISHES, 'Basement Finishes'),
)

WEEKLY = '01'
BIWEEKLY = '02'
SEMIMONTHLY = '03'
MONTHLY = '04'
DAILY = '05'

PAYPERIOD_CHOICES = (
    (WEEKLY, 'Weekly'),
    (BIWEEKLY, 'Bi-Weekly'),
    (SEMIMONTHLY, 'Semi-Monthly'),
    (MONTHLY, 'Monthly'),
    (DAILY, 'Daily'),
)

class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

def geocode(address):
    # google maps client set up
    google_maps_api_key = 'AIzaSyDCd2Zzq_FCPUagE4Plp-mNbvIJEJgY9Dg'
    gmaps = googlemaps.Client(key=google_maps_api_key)
    geocode_result = gmaps.geocode(address)

    lat = geocode_result[0]['geometry']['location']['lat']
    lng = geocode_result[0]['geometry']['location']['lng']

    return lat, lng

class Client(models.Model):
    name = models.CharField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Project(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=400)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    lat = models.FloatField(blank=True, null=True)
    lng = models.FloatField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.lat is None or self.lng is None:
            self.lat, self.lng = geocode(self.address)
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.address

class SubContractor(models.Model):
    name = models.CharField(max_length=200)
    ein_number = models.CharField(max_length=200, blank=True, null=True)
    license_number = models.CharField(max_length=200, blank=True, null=True)

    main_contact = models.CharField(max_length=200, blank=True, null=True)
    phone_number = models.CharField(max_length=200, blank=True, null=True)

    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

class SubContractorProject(models.Model):
    description = models.TextField()
    price = models.FloatField()

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    subcontractor = models.ForeignKey(SubContractor, on_delete=models.CASCADE)

    division_choice = models.CharField(
        max_length=2,
        choices=DIVISION_CHOICES,
        blank=True,
        null=True,
    )

    def __str__(self):
        return str(self.subcontractor.name) + ' | ' + str(self.project.name) + ' | ' + str(self.description)


class Day(models.Model):
    date = models.DateField(unique=True)
    slug = models.SlugField()

    def __str__(self):
        return str(self.date)

class SubContractorPayment(models.Model):
    amount = models.FloatField()
    subcontractor_project = models.ForeignKey(SubContractorProject, on_delete=models.CASCADE)
    day = models.ForeignKey(Day, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.subcontractor_project) + ' | ' + str(self.amount) + ' | ' + str(self.day)

class SubContractorProjectDay(models.Model):
    description = models.TextField(blank=True, null=True)
    subcontractor_project = models.ForeignKey(SubContractorProject, on_delete=models.CASCADE)

    division_choice = models.CharField(
        max_length=2,
        choices=DIVISION_CHOICES,
    )

    day = models.ForeignKey(Day, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return '(' + str(self.subcontractor_project.subcontractor) + ')'

class Income(models.Model):
    amount = models.FloatField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    day = models.ForeignKey(Day, on_delete=models.CASCADE)

class Employee(models.Model):
    name = models.CharField(max_length=200)
    base_salary = models.FloatField(blank=True, null=True)

    salaried = models.BooleanField(blank=True, null=True)
    foreman = models.BooleanField(blank=True, null=True)

    pay_period = models.CharField(
        max_length=2,
        choices=PAYPERIOD_CHOICES,
        blank=True,
        null=True
    )

    daily_pay = models.FloatField(blank=True, null=True, editable=False)

    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if not self.daily_pay:
            if self.pay_period == '05':
                self.daily_pay = self.base_salary
            elif self.pay_period == '04':
                self.daily_pay = self.base_salary/30
            elif self.pay_period == '03':
                self.daily_pay = self.base_salary/15
            elif self.pay_period == '02':
                self.daily_pay = self.base_salary/14
            elif self.pay_period == '01':
                self.daily_pay = self.base_salary/7
            print(self.daily_pay)
        super(Employee, self).save(*args, **kwargs)

    def __str__(self):
        return self.name + ' (' + ('Not Salaried', 'Salaried')[self.salaried==True] +  '| ' + ('Laborer', 'Foreman')[self.foreman==True] + ')'

class EmployeeSalaryAdjustment(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    amount = models.IntegerField()

    def __str__(self):
        return str(self.employee) + ' ' + str(self.amount)

class EmployeeCalculatedPay(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    amount = models.FloatField()

    def __str__(self):
        return str(self.employee) + ' calculated pay: ' + str(self.amount)

class WorkDay(models.Model):
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    employee = models.ManyToManyField(Employee, blank=True)
    employee_salary_adjustment = models.ManyToManyField(EmployeeSalaryAdjustment, blank=True)
    employee_calculated_salary = models.ManyToManyField(EmployeeCalculatedPay, blank=True, editable=False)

    division_choice = models.CharField(
        max_length=2,
        choices=DIVISION_CHOICES,
    )

    day = models.ForeignKey(Day, on_delete=models.SET_NULL, blank=True, null=True)
    def __str__(self):
        return '(' + str(self.project.name) + ')'

class File(models.Model):
    file = models.FileField(upload_to='attachments')
    day = models.ForeignKey(Day, on_delete=models.SET_NULL, blank=True, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.file)

class Expense(models.Model):
    amount = models.FloatField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='attachments', blank=True)
    day = models.ForeignKey(Day, on_delete=models.SET_NULL, blank=True, null=True)

    division_choice = models.CharField(
        max_length=2,
        choices=DIVISION_CHOICES,
    )

    def __str__(self):
        return str(self.amount)

expenses/templates/calendar.html
<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script
src="https://code.jquery.com/jquery-3.1.1.min.js"
integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>


{% load staticfiles %}
<link href="{% static 'dist/equinox.css' %}" rel="stylesheet">
<script src="{% static 'dist/equinox.min.js' %}"></script>

<script>
    const myEvents = [
        {% for day, details in days.items %}
        {
          start: '{{  day.date }}',
          end: '{{  day.date }}',
          title: '{{ day.date }} ({% for project in details.projects %}{{ project.name }}{% if not forloop.last %}; {% endif %}{% endfor %})',
          url: '{%url 'day_detail' slug=day.slug %}'
        },
        {% endfor %}
    ];

    $(function() {
        $('.event-calendar').equinox({
            events: myEvents
        });
    })
</script>


<body>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="event-calendar"></div>

</body>
</html>

expenses/templates/day_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>

    <!-- Latest compiled and minified Locales -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/locale/bootstrap-table-en-US.min.js"></script>

    <style>
        .display {
            width: 400px;
        }
    </style>
    <script>
    {% if workday.file_set %}
            var media_assets = []
            {% for file in workday.file_set.all %}
                {% load static %}
                media_assets.push("{% get_static_prefix %}{{ file.file }}");
            {% endfor %}

    function display_assets () {
        $.each(media_assets, function(i, v) {
                if (v.indexOf('.jpg') !== -1 || v.indexOf('.jpeg') !== -1 || v.indexOf('.png') !== -1 || v.indexOf('.gif') !== -1) {
                    $('.media').append("<div><a href=" + v + "><img class='display' src=" + v+ "></a></div>");
                } else if (v.indexOf('.mov') !== -1 || v.indexOf('.mp4') !== -1) {
                    $('.media').append("<div><video width='400' preload controls><source src=" + v + " type='video/mp4'></video></div>");
                } else {
                    $('.media').append("<div><a href=" + v + ">" + v + "</a>");
                }
            })
    }
    {% endif %}
    </script>

    <meta charset="UTF-8">

</head>
<body {% if workday.file_set %}onload="display_assets()"{% endif %}>
{% load humanize %}
{% if day %}
    <h1>{{ day.date }}</h1>
    <a href="{% url 'admin:expenses_day_change' day.id %}">Edit Day</a>
    {% for id, project in day.projects.items %}
        <h2><a href="{%url 'project_detail' slug=project.project.slug %}">{{ project.project }}</a></h2>
        {% if project.work_days %}
            <h2><u>Laborers</u></h2>
            {% for work_day in project.work_days %}
                <h3>Description</h3>
                {{ work_day.description|linebreaks }}
                <h3>Employees</h3>
                {% for employee in work_day.employee.all %}<a href="{%url 'employee_detail' slug=employee.slug %}">{{ employee.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
                (Labor Spend: {{ work_day.daily_labor_spend|floatformat:"2"|intcomma }})
                <h3>Construction Division</h3>
                 {{ work_day.get_division_choice_display }}
                {% if workday.file_set.all %}
                    <h3>Media</h3>
                    <div class="media">
                    </div>
                    {% for file in workday.file_set.all %}test{% endfor %}
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if project.expenses %}
            <h2><u>Expenses</u></h2>
            {% for expense in project.expenses %}
                {{ expense.amount }} | ({{ expense.description }}) | {{ expense.get_division_choice_display }}
                {% if expense.file %}
                    <p><a href="{% get_static_prefix %}{{ expense.file }}"><img class="display"src="{% get_static_prefix %}{{ expense.file }}"></a></p>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if project.total_subcontractor_spend or project.subcontractorproject_days %}
            <h2><u>Sub Contractors</u></h2>
            {{ project.total_subcontractor_spend }}
        {% endif %}
        {% if project.files %}
            <h2><u>Files</u></h2>
            {% for file in project.files %}
                <p><a href="{% get_static_prefix %}{{ file }}"><img class="display"src="{% get_static_prefix %}{{ file }}"></a></p>
            {% endfor %}
        {% endif %}
        <h3>Total Daily Labor Cost for Project</h3>
        {{ project.total_labor_spend|floatformat:"2"|intcomma }}
        <h3>Total Daily Non-Labor Expenses for Project</h3>
        {{ project.total_expense_spend|floatformat:"2"|intcomma }}
        <h3>Total Daily Cost for Project</h3>
        {{ project.daily_total_spend|floatformat:"2"|intcomma }}
        <hr>
    {% endfor %}
    <h2>Daily Total Spend: {{ daily_total_spend|floatformat:"2"|intcomma }}</h2>
{% endif %}
</body>
</html>

expenses/templates/employee_detail.html
<!DOCTYPE html>
<html>
    <head lang="en">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css">


    <script>
        $(function () {
            var $table = $('#table');
            var $search = $table.data('bootstrap.table')
                .$toolbar.find('.search input');
            $search.attr('placeholder', 'Search');
            $('.search').toggleClass('pull-right').toggleClass('pull-left');
        });

    </script>
    <style>
        .table-responsive{
            overflow-y: hidden;
        }
    </style>

</head>
<body>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if employee %}
    <h3>Projects</h3>
    {%  for project in projects %}
        <h4>{{ project.address }}</h4>
    {% for day in project.days %}
        <div><a href="{%url 'day_detail' slug=day.slug %}">{{ day.date }}</a></div>
    {% endfor %}
        <div>{{ project.employee_labor_spend }}</div>
    {% endfor %}
    <h4>Total Labor Spend {{ total_labor_spend }}</h4>

{% endif %}
</body>

expenses/templates/expense_search.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script
src="https://code.jquery.com/jquery-3.1.1.min.js"
integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
crossorigin="anonymous"></script>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(function() {
        $('#start-datepicker').datepicker();
        $('#end-datepicker').datepicker();
    })

    $(document).ready(function() {
        $('#query-form').submit(function(e) {
            e.preventDefault();

            expense_amount = $('#expense-amount').val();
            url_pattern  = '?expense=' + expense_amount;

            console.log(url_pattern);
            window.open('/expense_search/' + url_pattern, '_self');
        })
    })
</script>

<body>
{% load humanize %}
{% if expenses %}
    {% for expense in expenses %}
        <p>{{ expense.amount }} | <a href="{%url 'project_detail' slug=expense.project.slug %}">{{ expense.project }}</a> | {{ expense.description }} | <a href="{%url 'day_detail' slug=expense.day.slug %}">{{ expense.day }}</a> | {{ expense.get_division_choice_display }}</p>
    {% endfor %}
{% else %}
    <h3>Expense Amount</h3>
    <form id="query-form" autocomplete="off">
        <p><h3>Amount</h3><input type="text" id="expense-amount"></p>
    <button type="submit" form="query-form">Search</button>
    </form>
{% endif %}
</body>
</html>

expenses/templates/workday_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>

    <!-- Latest compiled and minified Locales -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/locale/bootstrap-table-en-US.min.js"></script>

    <style>
        .display {
            width: 400px;
        }
    </style>
    <script>
    {% if workday.file_set %}
            var media_assets = []
            {% for file in workday.file_set.all %}
                {% load static %}
                media_assets.push("{% get_static_prefix %}{{ file.file }}");
            {% endfor %}

    function display_assets () {
        $.each(media_assets, function(i, v) {
                if (v.indexOf('.jpg') !== -1 || v.indexOf('.jpeg') !== -1 || v.indexOf('.png') !== -1 || v.indexOf('.gif') !== -1) {
                    $('.media').append("<div><a href=" + v + "><img class='display' src=" + v+ "></a></div>");
                } else if (v.indexOf('.mov') !== -1 || v.indexOf('.mp4') !== -1) {
                    $('.media').append("<div><video width='400' preload controls><source src=" + v + " type='video/mp4'></video></div>");
                } else {
                    $('.media').append("<div><a href=" + v + ">" + v + "</a>");
                }
            })
    }
    {% endif %}
    </script>

    <meta charset="UTF-8">

</head>
<body {% if workday.file_set %}onload="display_assets()"{% endif %}>
{% if workday %}
    <h1>{{ workday.date }}</h1><a href="{% url 'admin:expenses_workday_change' workday.id %}">Edit Work Day</a>
    <h2>{{ workday.project }}</h2>
    <h3>Description</h3>
    {{ workday.description|linebreaks }}
    <h3>Laborers</h3>
    {% for employee in workday.employee.all %}<a href="{%url 'employee_detail' slug=employee.slug %}">{{ employee.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
        {% if expenses %}
    <h3>Expenses</h3>
        {% for expense in expenses %}
            {{ expense.amount }} | {{ expense.description }}
            {% if expense.file %}
            <p><a href="{% get_static_prefix %}{{ expense.file }}"><img class="display"src="{% get_static_prefix %}{{ expense.file }}"></a></p>
            {% endif %}
        {% endfor %}
    {% endif %}
    <h3>Daily Total Labor Cost</h3>
    {% if daily_spend %}{{ daily_spend }}{% endif %}
    <h3>Daily Total Expense</h3>
    {{ daily_expense_spend }}
    <h3>Daily Total Spend</h3>
    {{ daily_total_spend }}
    {% if workday.construction_division %}
    <h3>Construction Division</h3>
          <p>{{ workday.construction_division.get_division_choice_display }}</p>
    {% endif %}
    {% if workday.file_set.all %}
        <h3>Media</h3>
        <div class="media">
        </div>
        {% for file in workday.file_set.all %}test{% endfor %}
    {% endif %}
{% endif %}
</body>
</html>